name: Automerge dependabot PRs

on:
  pull_request_target:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        id: branch-name
        uses: tj-actions/branch-names@v6

      - name: Print branch name
        run: |
          echo "branch: ${{ steps.branch-name.outputs.current_branch }}"

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build code
        run: echo "build something..."

      - name: Test
        run: echo "test something..."

  automerge:
    needs: build
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write
      contents: write

    if: github.actor == 'dependabot[bot]'
    steps:
      - name: Auto approve
        uses: hmarr/auto-approve-action@v3

      - name: Automerge
        uses: "pascalgn/automerge-action@v0.15.6"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_LABELS: "dependencies"
          MERGE_DELETE_BRANCH: true
